### ISSUE TITLE
Placebo Mod spams my Console with WARN messages

### ISSUE THREAD

**Issue by atraum** [Shadows-of-Fire/Placebo#2]
Im using the mods from Tekxit 3 and some others.

Check out Latest.log and search for "placebo" . You will see it soon spamming with WARNING and a lot of Info.

I hope you can "fix" this or write some lines so i can manually turn this off in the config.

This would be very useful.

And this is my first problem post ever, for the info.

[latest.log](https://github.com/Shadows-of-Fire/Placebo/files/2812488/latest.log)
[debug.log](https://github.com/Shadows-of-Fire/Placebo/files/2812489/debug.log)

**Comment by Shadows-of-Fire** [comment]
Working as intended.  The log spam is just fake errors logged by fml for using replacement

**Comment by atraum** [comment]
Ok, i dont know much about that. 

Do you have a solution?

**Comment by Shadows-of-Fire** [comment]
There's no way to shut off that warning, annoyingly enough.

**Comment by atraum** [comment]
Ou damn. 

Ok thank you for your time.

**Comment by katubug** [comment]
I'm sorry to bother, but are you certain there's no way to turn that warning off? It makes it very difficult to share my server logs with anyone because it insists on telling me that there's a "_Potentially Dangerous alternative prefix `rsgauges` for name `rustic/trapdorswitch_rustic2`, expected `placebo`. This could be a intended override, but in most cases indicates a broken mod_."

It does that for what seems to be every single item in the pack. And because my log files are so bloated, they're sometimes too big for pastebin/hastebin. Not to mention it makes it much harder to find legitimate issues hidden among the spam.

**Comment by Shadows-of-Fire** [comment]
https://www.curseforge.com/minecraft/mc-mods/stuff-a-sock-in-it

**Comment by katubug** [comment]
Thank you for the quick response! :) Unfortunately, I haven't had any luck with that mod, nor Console Filter. Either they don't work during startup, or I'm doing the config incorrectly. I asked both mod authors for help but never heard back.

Have you got it working, by any chance?

**Comment by Shadows-of-Fire** [comment]
I've never bothered to use any mod to filter logs as I am generally looking for a specific thing when I open them, and message filters are really not that useful.
