### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by ConnorEgbert** [Shadows-of-Fire/Placebo#85]
Game hangs for seconds at a time, increasing in frequency with play time. 

```
Exception loading patreon data!
[shadows.placebo.patreon.PatreonManager:lambda$init$0:66]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Link to relevant line:
 
https://github.com/Shadows-of-Fire/Placebo/blob/0c91489d42ede39b25ddf03f5c93e5c242fc8686/src/main/java/shadows/placebo/patreon/PatreonManager.java#L46

The certificate for raw.githubusercontent.com seems fine when verified outside minecraft. This issue is repeatable when running rlcraft 2.9.3 on startup from Placebo, and frequently when mods like Elenai Dodge use Placebo's patreon interface. Please advise.

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported.  

In general, this code runs off-thread, so it isn't capable of locking up the game as described, nor does this code execute more than once per texture load.  I'm concerned by the concept of "when mods use Placebo's patreon interface", since this isn't a reusable component, nor any kind of API.  Potentially that might be your issue if another mod is spam-calling `init()`.
