### ISSUE TITLE
DataGen mixin crash

### ISSUE THREAD

**Issue by notoriousgtw** [Shadows-of-Fire/Placebo#93]
I'm getting a crash related to the anvil mixin when I try to generate resources
[latest.log](https://github.com/user-attachments/files/16881754/latest.log)
[debug.log](https://github.com/user-attachments/files/16881760/debug.log)

**Comment by notoriousgtw** [comment]
Sorry,
Version 8.6.2 for 1.20.1

**Comment by Shadows-of-Fire** [comment]
Do you have mixingradle applied? It's required to load deps with obfuscated mixins so the refmaps are not applied (otherwise the obfuscated targets, which do not exist in dev, will be searched for).  From the crash log you've provided, it seems like you _don't_ have mixingradle loaded, as the mixin is searching for an obfuscated target.

**Comment by notoriousgtw** [comment]
That was definitely it, thank you!
